using System;
using System.Collections.Generic;

namespace SmartERPDashboard.Services;

public class LocalizationService
{
    public bool IsArabic { get; private set; } = true;
    public event Action? OnLanguageChanged;

    public void ToggleLanguage()
    {
        IsArabic = !IsArabic;
        OnLanguageChanged?.Invoke();
    }

    public string Dir => IsArabic ? "rtl" : "ltr";

    private readonly Dictionary<string, string> _ar = new()
    {
        {"Academic Demo", "مشروع التخرج"},
        {"Research Dashboard", "لوحة القياس التفاعلية"},
        {"Overview", "نظرة عامة"},
        {"Tech Toolkit", "التقنيات الحديثة"},
        {"Customer Experience", "تجربة العملاء"},
        {"Academic Research Dashboard", "لوحة معلومات بحثية تفاعلية"},
        {"The Role of Modern Technology<br />in Organizational Competitiveness", "دور التكنولوجيا الحديثة<br />في التنافسية المؤسسية"},
        {"Toggle between states to visualize the measurable impact of digital transformation on key business metrics.", "قم بالتبديل لرؤية الأثر المباشر للتحول الرقمي على مؤشرات الأداء الرئيسية."},
        {"Before Tech", "الطرق التقليدية"},
        {"After Tech", "التحول الرقمي"},
        {"Currently viewing:", "أنت تشاهد الآن:"},
        {"✅ Post-Digital Transformation", "✅ بعد التحول الرقمي"},
        {"⚠️ Pre-Digital Transformation", "⚠️ قبل التحول الرقمي"},
        {"Key Performance Indicators", "مؤشرات الأداء الرئيسية (KPIs)"},
        {"Revenue Growth vs. Market Competitors", "نمو الإيرادات مقابل المنافسين"},
        {"Quarterly revenue index — Organization vs. Industry Average", "مؤشر الإيرادات الربع سنوي — مؤسستنا مقابل متوسط السوق"},
        {"Our Organization", "مؤسستنا"},
        {"Competitors", "المنافسين"},
        
        // Tech Toolkit
        {"Core Technologies Driving Competitiveness", "التقنيات الأساسية الدافعة للتنافسية"},
        {"Strategic Tech Stack", "حزمة التقنيات الاستراتيجية"},
        {"Explore how specific digital tools transform operations and create sustainable competitive advantages.", "استكشف كيف تقوم الأدوات الرقمية بتحويل العمليات وخلق مزايا تنافسية مستدامة."},
        {"System Components", "مكونات النظام الأساسية"},
        
        {"Digital Infrastructure", "البنية التحتية الرقمية"},
        {"Technology Toolkit", "أدوات التكنولوجيا"},
        {"Explore the four pillars of modern technology that drive organizational competitiveness and sustainable growth.", "استكشف الركائز الأربع للتكنولوجيا الحديثة التي تدفع التنافسية المؤسسية والنمو المستدام."},
        {"Proven Competitive Advantage", "ميزة تنافسية مثبتة"},
        
        // Customer Experience
        {"Customer-Centric Automation", "أتمتة تركز على العميل"},
        {"Customer Experience Simulation", "محاكاة تجربة العملاء"},
        {"Witness how automation and AI deliver lightning-fast service and around-the-clock intelligent support.", "شاهد كيف توفر الأتمتة والذكاء الاصطناعي خدمة سريعة ودعم ذكي على مدار الساعة."},
        {"Smart Order Tracker", "المتتبع الذكي للطلبات"},
        {"Automated fulfillment pipeline in real-time", "تتبع حي للطلبات بشكل آلي بالكامل"},
        {"Simulate Order", "محاكاة طلب جديد"},
        {"Simulating…", "جاري المحاكاة..."},
        {"Simulate Again", "محاكاة مرة أخرى"},
        {"Automation running…", "عمليات الأتمتة قيد التنفيذ..."},
        {"Order Delivered! ✅ Customer satisfaction secured.", "تم تسليم الطلب بنجاح! ✅"},
        {"24/7 AI Support Bot", "روبوت الدعم الذكي 24/7"},
        {"Click a question to see instant AI-powered responses", "اضغط على سؤال لرؤية الرد الفوري المدعوم بالذكاء الاصطناعي"},
        
        {"Order Placed", "تم تأكيد الطلب"},
        {"Received & validated instantly", "تم الاستلام والتحقق فوراً"},
        {"Processing", "قيد المعالجة"},
        {"AI picks the optimal warehouse route", "الذكاء الاصطناعي يختار أفضل مسار"},
        {"Shipped", "تم الشحن"},
        {"Out for delivery via smart logistics", "في الطريق إليك عبر لوجستيات ذكية"},
        {"Delivered", "تم التوصيل"},
        {"Confirmed at destination ✔", "تم تأكيد الوصول ✔"},
        
        // Chatbot UI
        {"ERP Smart Assistant", "مساعد ذكي للنظام"},
        {"Always online · AI-powered", "متصل دائماً · مدعوم بالذكاء الاصطناعي"},
        {"Suggested questions:", "أسئلة مقترحة:"},
        {"👋 Hello! I'm your 24/7 AI assistant. How can I help you today?", "👋 أهلاً بك! أنا المساعد الذكي. كيف يمكنني مساعدتك اليوم؟"},
        
        // Mock Data
        {"Sales Growth", "نمو المبيعات"},
        {"Operational Costs", "التكاليف التشغيلية"},
        {"Customer Satisfaction", "رضا العملاء"},
        {"Avg Response Time", "متوسط وقت الاستجابة"},
        {"min", "دقيقة"},
        {"hrs", "ساعة"},
        {"High", "مرتفع"},
        {"Slow", "بطيء"},
        {"Our Organization (Post-Tech)", "مؤسستنا (بعد التكنولوجيا)"},
        {"Our Organization (Pre-Tech)", "مؤسستنا (قبل التكنولوجيا)"},
        {"📦  Where is my order?", "📦 أين طلبي؟"},
        {"Your order #ORD-8821 is currently **Out for Delivery** and is expected at your door within 2 hours. You can track it live on our map. 🚚", "طلبك رقم #ORD-8821 حالياً **في الطريق إليك** ومن المتوقع وصوله خلال ساعتين. يمكنك تتبعه مباشرة على الخريطة. 🚚"},
        {"💳  How do I get a refund?", "💳 كيف أسترد أموالي؟"},
        {"Refunds are processed instantly to your original payment method. Simply go to **My Orders → Request Refund** and we will credit you within 24 hours. ✅", "تتم معالجة المبالغ المستردة فوراً إلى طريقة الدفع الأصلية. فقط اذهب إلى **طلباتي → طلب استرجاع** وسنقوم بتحويل المبلغ خلال 24 ساعة. ✅"},
        {"🕐  What are your support hours?", "🕐 ما هي ساعات العمل للدعم الفني؟"},
        {"Our AI support is available **24 hours a day, 7 days a week, 365 days a year** — no waiting, no queues. Human agents are on call Mon–Fri 9 AM–6 PM for escalations. 🤖", "دعم الذكاء الاصطناعي متوفر **24 ساعة في اليوم، 7 أيام في الأسبوع، 365 يوماً في السنة** — بدون انتظار أو طوابير. ويتوفر عملاء بشريون من الاثنين للجمعة من 9 صباحاً لـ 6 مساءً. 🤖"},

        // Tech Tools
        {"Cloud Computing", "الحوسبة السحابية"},
        {"Scalable, on-demand infrastructure.", "بنية تحتية مرنة وقابلة للتوسع."},
        {"Cloud computing eliminated costly on-premise servers, reducing IT infrastructure spend by 45% and enabling instant global scalability.", "ألغت الحوسبة السحابية الحاجة للسيرفرات المحلية المكلفة، مما قلل من نفقات البنية التحتية بنسبة 45% ومكّن من التوسع العالمي الفوري."},
        {"Real-time data access from any location accelerated decision-making cycles by 60%, giving the organization a decisive edge over slower, legacy-bound competitors.", "الوصول الفوري للبيانات من أي مكان سرّع من دورات اتخاذ القرار بنسبة 60%، مما أعطى المنظمة ميزة حاسمة على المنافسين."},
        {"Artificial Intelligence", "الذكاء الاصطناعي"},
        {"Predictive analytics & smart automation.", "التحليلات التنبؤية والأتمتة الذكية."},
        {"AI-powered demand forecasting reduced inventory waste by 38% and boosted on-time deliveries to 97%, directly improving the bottom line.", "قلل التنبؤ بالطلب المدعوم بالذكاء الاصطناعي من هدر المخزون بنسبة 38% ورفع نسبة التسليم في الوقت المحدد إلى 97%."},
        {"Machine-learning recommendation engines increased average order value by 27% by surfacing hyper-personalized product suggestions at the right moment.", "زادت محركات التوصية المعتمدة على تعلم الآلة من متوسط قيمة الطلب بنسبة 27% عبر تقديم اقتراحات مخصصة في الوقت المناسب."},
        {"Robotic Process Automation", "أتمتة العمليات الروبوتية (RPA)"},
        {"End-to-end workflow automation.", "أتمتة سير العمل بالكامل."},
        {"RPA bots handle 85% of repetitive back-office tasks — invoice processing, data entry, and reconciliation — without a single human touch.", "تتولى روبوتات RPA ما يصل إلى 85% من المهام المكتبية المتكررة — كمعالجة الفواتير وإدخال البيانات — بدون أي تدخل بشري."},
        {"This freed 1,200+ employee-hours per month, which were reallocated to high-value strategic work, compressing quarterly close cycles from 10 days to 2.", "هذا وفر أكثر من 1200 ساعة عمل شهرياً، وتم إعادة توجيهها للأعمال الاستراتيجية الهامة."},
        {"Smart Payment Systems", "أنظمة الدفع الذكية"},
        {"Frictionless, secure digital transactions.", "معاملات رقمية آمنة وسلسة."},
        {"Integrating AI-fraud-detection into the payment gateway reduced chargebacks by 92% and cut false-positive declines, recovering an estimated $2.1 M annually.", "دمج كشف الاحتيال بالذكاء الاصطناعي في بوابة الدفع قلل من المرتجعات بنسبة 92% واسترد ما يقدر بـ 2.1 مليون دولار سنوياً."},
        {"One-click checkout and multi-wallet support (Apple Pay, Google Pay, BNPL) lifted cart conversion rates by 33%, directly boosting quarterly revenue.", "دعم الدفع بنقرة واحدة والمحافظ المتعددة رفع من معدلات تحويل السلة بنسبة 33% مما زاد من الإيرادات مباشرة."},

        // Navigation Additions
        {"ROI Calculator", "حاسبة العائد على الاستثمار"},
        {"Operations", "العمليات"},
        {"Collaboration", "التعاون"},

        // ROI Calculator
        {"Investment Analysis", "تحليل الاستثمار"},
        {"Digital Transformation ROI Calculator", "حاسبة العائد على الاستثمار للتحول الرقمي"},
        {"Calculate your projected return on investment from implementing modern ERP technologies.", "احسب العائد المتوقع على الاستثمار من تطبيق تقنيات تخطيط موارد المؤسسات (ERP) الحديثة."},
        {"Your Organization", "مؤسستك"},
        {"Enter your details to see personalized projections", "أدخل بياناتك لعرض التوقعات المخصصة"},
        {"Industry", "قطاع العمل"},
        {"Number of Employees", "عدد الموظفين"},
        {"Annual Revenue ($)", "الإيرادات السنوية ($)"},
        {"Current Annual Tech Spend ($)", "الإنفاق التقني السنوي الحالي ($)"},
        {"Calculate ROI", "حساب العائد"},
        {"Projected Results", "النتائج المتوقعة"},
        {"Based on industry benchmarks and your inputs", "بناءً على معايير القطاع والبيانات المدخلة"},
        {"Annual Savings", "التوفير السنوي"},
        {"efficiency gain", "زيادة في الكفاءة"},
        {"Payback Period (months)", "فترة الاسترداد (بالأشهر)"},
        {"Break-even timeline", "الجدول الزمني للوصول لنقطة التعادل"},
        {"3-Year ROI", "العائد على مدى 3 سنوات"},
        {"Cumulative return", "العائد التراكمي"},
        {"Savings per Employee", "التوفير لكل موظف"},
        {"Annual benefit per person", "العائد السنوي لكل شخص"},
        {"Industry Benchmarks", "معايير قطاع العمل"},
        {"Efficiency", "الكفاءة"},
        {"Cost Reduction", "خفض التكاليف"},
        {"Technology", "التكنولوجيا"},
        {"SaaS and software companies see high automation gains", "شركات البرمجيات تشهد مكاسب عالية من الأتمتة"},
        {"Manufacturing", "التصنيع"},
        {"Smart factories and IoT integration drive major improvements", "المصانع الذكية وإنترنت الأشياء يقودان تحسينات كبرى"},
        {"Retail", "التجزئة"},
        {"Inventory automation and AI forecasting transform operations", "أتمتة المخزون والتنبؤ بالذكاء الاصطناعي يحولان مسار العمليات"},
        {"Healthcare", "الرعاية الصحية"},
        {"Digital patient records and automated scheduling save time", "السجلات الرقمية والجدولة الآلية توفران الكثير من الوقت"},
        {"Finance", "التمويل"},
        {"RPA in compliance and trading delivers strong ROI", "أتمتة العمليات الروبوتية توفر عائداً قوياً في الامتثال والتداول"},
        {"Logistics", "الخدمات اللوجستية"},
        {"Route optimization and warehouse automation are game-changers", "تحسين المسارات وأتمتة المستودعات تغيّر قواعد اللعبة"},
        {"Cumulative Savings", "التوفير التراكمي"},
        {"Tech Investment", "الاستثمار التقني"},
        {"Year 1", "السنة 1"},
        {"Year 2", "السنة 2"},
        {"Year 3", "السنة 3"},

        // Operations Center
        {"Operational Excellence", "التميز التشغيلي"},
        {"Operations & Efficiency Center", "مركز العمليات والكفاءة"},
        {"Experience how automation transforms production, inventory, and quality workflows in real-time.", "اكتشف كيف تحوّل الأتمتة سير عمل الإنتاج والمخزون والجودة في الوقت الفعلي."},
        {"Efficiency Gain", "زيادة الكفاءة"},
        {"Weekly Time Saved", "الوقت الموفر أسبوعياً"},
        {"Before Tech:", "قبل التكنولوجيا:"},
        {"After Tech:", "بعد التكنولوجيا:"},
        {"time saved", "وقت مُوفّر"},
        {"Running Simulation...", "جاري تشغيل المحاكاة..."},
        {"Restart Simulation", "إعادة تشغيل المحاكاة"},
        {"Run Workflow Simulation", "تشغيل محاكاة سير العمل"},
        {"Automated Tasks", "المهام المؤتمتة"},
        {"Efficiency Impact Summary", "ملخص تأثير الكفاءة"},
        {"Faster", "أسرع"},
        {"Saved/Week", "مُوفّر/أسبوع"},
        {"Smart Inventory Management", "الإدارة الذكية للمخزون"},
        {"AI-powered demand forecasting and automated reordering", "التنبؤ بالطلب بالذكاء الاصطناعي وإعادة الطلب آلياً"},
        {"AI Demand Forecasting", "التنبؤ بالطلب بالذكاء الاصطناعي"},
        {"Machine learning predicts stock needs 30 days ahead", "تعلم الآلة يتنبأ باحتياجات المخزون قبل 30 يوماً"},
        {"Analyze historical data", "تحليل البيانات التاريخية"},
        {"Predict seasonal trends", "التنبؤ بالاتجاهات الموسمية"},
        {"Generate forecast reports", "إنشاء تقارير التوقعات"},
        {"Automated Reordering", "إعادة الطلب الآلي"},
        {"System places orders when stock hits threshold", "يُصدر النظام طلبات عند وصول المخزون للحد الأدنى"},
        {"Check stock levels", "فحص مستويات المخزون"},
        {"Calculate optimal order qty", "حساب كمية الطلب المثلى"},
        {"Send PO to suppliers", "إرسال أمر الشراء للموردين"},
        {"Real-Time Tracking", "التتبع في الوقت الفعلي"},
        {"Live visibility of shipments and delivery status", "رؤية حية للشحنات وحالة التسليم"},
        {"Monitor shipments", "مراقبة الشحنات"},
        {"Update inventory", "تحديث المخزون"},
        {"Notify stakeholders", "إشعار أصحاب المصلحة"},
        {"Production Line Optimization", "تحسين خط الإنتاج"},
        {"IoT sensors and predictive maintenance scheduling", "مستشعرات إنترنت الأشياء وجدولة الصيانة التنبؤية"},
        {"IoT Monitoring", "مراقبة إنترنت الأشياء"},
        {"Sensors track equipment health in real-time", "المستشعرات تتتبع حالة المعدات في الوقت الفعلي"},
        {"Collect sensor data", "جمع بيانات المستشعرات"},
        {"Detect anomalies", "اكتشاف الحالات الشاذة"},
        {"Alert maintenance team", "تنبيه فريق الصيانة"},
        {"Predictive Maintenance", "الصيانة التنبؤية"},
        {"AI predicts failures before they happen", "الذكاء الاصطناعي يتنبأ بالأعطال قبل حدوثها"},
        {"Analyze wear patterns", "تحليل أنماط التآكل"},
        {"Schedule maintenance", "جدولة الصيانة"},
        {"Order replacement parts", "طلب قطع الغيار"},
        {"Auto-Optimization", "التحسين الآلي"},
        {"System adjusts parameters for peak efficiency", "يضبط النظام المعايير لتحقيق أقصى كفاءة"},
        {"Adjust line speed", "تعديل سرعة الخط"},
        {"Optimize energy use", "تحسين استخدام الطاقة"},
        {"Balance workloads", "موازنة أعباء العمل"},
        {"Quality Assurance Automation", "أتمتة ضمان الجودة"},
        {"Computer vision and automated defect detection", "الرؤية الحاسوبية والكشف الآلي عن العيوب"},
        {"Automated Scanning", "المسح الآلي"},
        {"Computer vision inspects every unit", "الرؤية الحاسوبية تفحص كل وحدة"},
        {"Capture product images", "التقاط صور للمنتج"},
        {"Detect defects", "اكتشاف العيوب"},
        {"Flag issues instantly", "الإبلاغ عن المشكلات فوراً"},
        {"Instant Reporting", "التقارير الفورية"},
        {"Quality dashboards update in real-time", "تحديث لوحات معلومات الجودة في الوقت الفعلي"},
        {"Generate QC reports", "إنشاء تقارير مراقبة الجودة"},
        {"Alert supervisors", "تنبيه المشرفين"},
        {"Update compliance logs", "تحديث سجلات الامتثال"},

        // Team Collaboration
        {"Connected Workforce", "القوى العاملة المتصلة"},
        {"Team Collaboration Hub", "مركز تعاون فريق العمل"},
        {"Discover how modern collaboration tools break down silos and accelerate teamwork across your organization.", "اكتشف كيف تكسر أدوات التعاون الحديثة الحواجز وتسرّع العمل الجماعي في مؤسستك."},
        {"Collaboration Impact", "تأثير التعاون"},
        {"Work Mode Productivity Index", "مؤشر إنتاجية نمط العمل"},
        {"Comparing productivity across different work arrangements", "مقارنة الإنتاجية عبر ترتيبات العمل المختلفة"},
        {"Hybrid", "هجين"},
        {"Remote", "عن بُعد"},
        {"Office", "من المكتب"},
        {"Collaboration Toolkit", "أدوات التعاون"},
        {"Explore the before and after of digital collaboration transformation", "استكشف ما قبل وما بعد التحول الرقمي للتعاون"},
        {"Before", "قبل"},
        {"After", "بعد"},
        {"Global Team Access", "وصول الفريق عالمياً"},
        {"Meeting Setup Time", "وقت إعداد الاجتماعات"},
        {"Cross-Functional Projects", "مشاريع متعددة التخصصات"},
        {"Employee Satisfaction", "رضا الموظفين"},
        {"Hybrid Work", "العمل الهجين"},
        {"Remote Work", "العمل عن بُعد"},
        {"Office Work", "العمل من المكتب"},
        {"Response Time", "وقت الاستجابة"},
        {"Average time to respond to team messages", "متوسط الوقت للرد على رسائل الفريق"},
        {"Meeting Efficiency", "كفاءة الاجتماعات"},
        {"Reduction in unnecessary meeting time", "تخفيض وقت الاجتماعات غير الضرورية"},
        {"Document Access", "الوصول للمستندات"},
        {"Uptime for cloud document storage", "وقت التشغيل لتخزين المستندات السحابية"},
        {"Cross-Team Projects", "مشاريع مشتركة بين الفِرَق"},
        {"Active collaborative projects this quarter", "المشاريع التعاونية النشطة هذا الربع"},
        {"Unified Messaging", "المراسلة الموحدة"},
        {"Communication", "التواصل"},
        {"Instant team communication across departments", "تواصل فوري بين الفرق عبر الأقسام"},
        {"Email chains with 24hr response delays", "سلاسل البريد الإلكتروني مع تأخيرات تصل لـ 24 ساعة"},
        {"Instant replies and threaded conversations", "ردود فورية ومحادثات متسلسلة منظمة"},
        {"Smart Video Conferencing", "مؤتمرات الفيديو الذكية"},
        {"Meetings", "الاجتماعات"},
        {"AI-powered meetings with transcription", "اجتماعات مدعومة بالذكاء الاصطناعي مع التفريغ النصي"},
        {"In-person meetings, travel time, no records", "اجتماعات حضورية، وقت ضائع في السفر، بلا سجلات"},
        {"Remote attendance, auto-transcription, action items", "حضور عن بُعد، تفريغ آلي، وعناصر عمل قابلة للتنفيذ"},
        {"Cloud Documents", "المستندات السحابية"},
        {"Documentation", "التوثيق"},
        {"Real-time collaborative editing", "تحرير تعاوني في الوقت الفعلي"},
        {"Version chaos, email attachments, conflicts", "فوضى الإصدارات، مرفقات البريد، وتعارض في التعديلات"},
        {"Single source of truth, simultaneous editing", "مصدر واحد للحقيقة، تحرير متزامن للجميع"},
        {"Project Management", "إدارة المشاريع"},
        {"Planning", "التخطيط"},
        {"Visual task tracking and automation", "تتبع مرئي للمهام وأتمتة العمليات"},
        {"Spreadsheets, status meetings, manual updates", "جداول بيانات، اجتماعات حالة، وتحديثات يدوية"},
        {"Real-time boards, automated workflows, alerts", "لوحات تفاعلية، سير عمل مؤتمت، وتنبيهات فورية"},
        {"Digital Whiteboard", "السبورة الرقمية"},
        {"Ideation", "طرح الأفكار"},
        {"Infinite canvas for team brainstorming", "مساحة لا نهائية لعصف الأفكار الجماعي"},
        {"Physical whiteboards, photo snapshots, no access", "سبورات فعلية، صور ملتقطة، ولا يمكن للجميع الوصول لها"},
        {"Persistent boards, async contribution, templates", "سبورات دائمة، مشاركة غير متزامنة، وقوالب جاهزة"},
        {"Knowledge Base", "قاعدة المعرفة"},
        {"Information", "المعلومات"},
        {"Searchable company wiki and FAQs", "ويكي للشركة وأسئلة شائعة قابلة للبحث"},
        {"Tribal knowledge, repeated questions, silos", "معرفة محتكرة، أسئلة متكررة، وانعزال معلوماتي"},
        {"Self-service answers, onboarding docs, search", "إجابات ذاتية، مستندات تأهيل، وبحث سريع"},
        {"Mon", "الإثنين"},
        {"Tue", "الثلاثاء"},
        {"Wed", "الأربعاء"},
        {"Thu", "الخميس"},
        {"Fri", "الجمعة"},

        // Login
        {"Welcome back", "مرحباً بعودتك"},
        {"Sign in to access your dashboard", "سجّل دخولك للوصول إلى لوحة التحكم"},
        {"Username", "اسم المستخدم"},
        {"Enter your username", "أدخل اسم المستخدم"},
        {"Password", "كلمة المرور"},
        {"Enter your password", "أدخل كلمة المرور"},
        {"Sign In", "تسجيل الدخول"},
        {"Signing in...", "جارٍ تسجيل الدخول..."},
        {"Please enter your username", "الرجاء إدخال اسم المستخدم"},
        {"Please enter your password", "الرجاء إدخال كلمة المرور"},
        {"Invalid username or password", "اسم المستخدم أو كلمة المرور غير صحيحة"},
        {"Academic Demo · Group 15", "مشروع تخرج · المجموعة 15"},
        {"Logout", "تسجيل الخروج"},
        
        // Aramex Case Study Pages
        {"Aramex Case Study", "دراسة حالة أرامكس"},
        {"Aramex Goals", "أهداف أرامكس الرقمية"},
        {"Aramex Importance", "الأهمية التنافسية لأرامكس"},
        {"Aramex Functions", "الأدوار التشغيلية الحديثة"},
        {"Aramex Challenges", "تحديات التحول في أرامكس"},
        {"Aramex Overview", "مركز حلول أرامكس"},
        {"SmartERP", "حلول أرامكس الذكية (Aramex Smart)"},
        {"Digital Transformation Impact is up", "ارتفع أثر التحول الرقمي بنسبة"}
    };

    public string T(string englishText)
    {
        if (!IsArabic) return englishText;
        return _ar.TryGetValue(englishText, out var arText) ? arText : englishText;
    }
}
